// STEP Apply — editable data file.
// To update: change the batch number, or set/replace a state's "url".
// - url: "" (empty) shows the state as "Coming soon" (grayed, not clickable)
// - url: a Google Form link, open: true  -> shows "Apply now" (clickable, accent button)
// - url: a Google Form link, open: false -> shows "Closed" (grayed, not clickable)
// Generated by admin.html — save this file and commit/upload it to GitHub.

window.STEP_DATA = {
  batch: "13",
  eligibility: "This programme is only for the final year students of Polytechnic Diploma.",
  states: [
    { name: "Andhra Pradesh", url: "https://docs.google.com/forms/d/e/1FAIpQLSdZo-HGIBQHAH4-XAByWj3fg6S_NyN7S_K0An0ZiUoYutKylQ/viewform", open: false },
    { name: "Delhi", url: "", open: false },
    { name: "Kerala", url: "https://forms.gle/EyhjkSA1FYp4Ud518", open: false },
    { name: "Maharashtra", url: "", open: false },
    { name: "Odisha", url: "", open: false },
    { name: "Telangana", url: "", open: false },
    { name: "Uttar Pradesh", url: "", open: false },
    { name: "Uttarakhand", url: "", open: false },
    { name: "West Bengal", url: "https://docs.google.com/forms/d/e/1FAIpQLScgE63AnI8kaJQbZqCYPYY2DJyS1wcui0efQY2MvW7sU3K2Rg/closedform", open: false }
  ]
};